services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.06"
          memory: "20MB"
    depends_on:
      - api1
      - api2
    networks:
      - rinha-network

  api1: &api-base
    build: .
    shm_size: '256mb'
    ipc: shareable
    environment:
      - PORT=3000
    deploy:
      resources:
        limits:
          cpus: "0.47"
          memory: "165MB"
    networks:
      - rinha-network

  api2:
    <<: *api-base
    ipc: service:api1
    deploy:
      resources:
        limits:
          cpus: "0.47"
          memory: "165MB"

networks:
  rinha-network:
    driver: bridge
